table 2020-2023
	lineageTag: 0c8f4e70-6c69-431f-a014-6fb5d1f0ee5b

	column 'Country / territory'
		dataType: string
		lineageTag: 4e8041c3-e467-4f83-a6bb-1ea00d49e0bb
		summarizeBy: none
		sourceColumn: Country / territory

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: a22a526d-e6d9-48ad-87e1-92aa0abc098f
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'GDP Per Capita ($)'
		dataType: int64
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 3e8b2ca5-fda1-40d5-84a6-875334bb9de4
		summarizeBy: sum
		sourceColumn: GDP Per Capita ($)

		annotation SummarizationSetBy = Automatic

	partition 2020-2023 = m
		mode: import
		source =
				let
				    Source = Web.BrowserContents("https://en.wikipedia.org/wiki/List_of_countries_by_past_and_projected_GDP_(nominal)_per_capita#2020s"),
				    #"Extracted Table From Html" = Html.Table(Source, {{"Column1", "TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR > :nth-child(1)"}, {"Column2", "TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR > :nth-child(2)"}, {"Column3", "TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR > :nth-child(3)"}, {"Column4", "TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR > :nth-child(4)"}, {"Column5", "TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR > :nth-child(5)"}}, [RowSelector="TABLE.sortable.wikitable.mw-datatable.static-row-numbers.col1left:nth-child(51) > * > TR"]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Extracted Table From Html",{{"Column1", type text}, {"Column2", Int64.Type}, {"Column3", Int64.Type}, {"Column4", Int64.Type}, {"Column5", Int64.Type}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Country / territory", type text}, {"2020", Int64.Type}, {"2021", Int64.Type}, {"2022", Int64.Type}, {"2023", Int64.Type}}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Changed Type1", {"Country / territory"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Year"}, {"Value", "GDP Per Capita ($)"}}),
				    #"Sorted Rows" = Table.Sort(#"Renamed Columns",{{"Country / territory", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

